// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1_38RevKKVUo-V4aP0dLHXtSlNBFmAdU',
    appId: '1:253303035771:web:2967de13ffed29dfab8fde',
    messagingSenderId: '253303035771',
    projectId: 'flutter-rpg-2b0f8',
    authDomain: 'flutter-rpg-2b0f8.firebaseapp.com',
    storageBucket: 'flutter-rpg-2b0f8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOfva_tH0sIQ49Op2pgmXSPkU_4PqPKkE',
    appId: '1:253303035771:android:07e030bec641db97ab8fde',
    messagingSenderId: '253303035771',
    projectId: 'flutter-rpg-2b0f8',
    storageBucket: 'flutter-rpg-2b0f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhQf7xDdbnAPLftXJZFMCzYu0eUaPWOuY',
    appId: '1:253303035771:ios:36a7a1d820e3e4c9ab8fde',
    messagingSenderId: '253303035771',
    projectId: 'flutter-rpg-2b0f8',
    storageBucket: 'flutter-rpg-2b0f8.firebasestorage.app',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhQf7xDdbnAPLftXJZFMCzYu0eUaPWOuY',
    appId: '1:253303035771:ios:36a7a1d820e3e4c9ab8fde',
    messagingSenderId: '253303035771',
    projectId: 'flutter-rpg-2b0f8',
    storageBucket: 'flutter-rpg-2b0f8.firebasestorage.app',
    iosBundleId: 'com.example.flutterRpg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1_38RevKKVUo-V4aP0dLHXtSlNBFmAdU',
    appId: '1:253303035771:web:349bacbc45ee021bab8fde',
    messagingSenderId: '253303035771',
    projectId: 'flutter-rpg-2b0f8',
    authDomain: 'flutter-rpg-2b0f8.firebaseapp.com',
    storageBucket: 'flutter-rpg-2b0f8.firebasestorage.app',
  );
}
